os:
  - linux
#  - osx  # Travis CI still does not support Python builds

language: python

python:
  - 3.3
  - 3.4
  - 3.5

# command to install dependencies
install:
  - pip install coveralls
  - pip install -e .
    
# command to run tests
script: 
  - cd tests/
  - coverage run -m unittest discover . -v
  - cp .coverage ../.coverage
  - cd ../

after_success:
  - coveralls
  